dist: trusty
sudo: required

install:
    - curl -L0 https://github.com/gohugoio/hugo/releases/download/v0.63.2/hugo_0.63.2_Linux-64bit.deb
    - sudo dpkg -i hugo0.63.2_Linux-0.63.2_Linux-64bit.deb

script:
    - hugo

deploy:
    - provider: script
      script: ./deploy.sh
      skip_cleanup:true
      on:
          branch: master
